// =============================================================================
// VoidEXT link pool
// -----------------------------------------------------------------------------
// This is the master list of links served (in rotation) to authenticated users.
// Storing them here on the server — rather than baking them into the bookmarklet
// — keeps the list private and prevents leaks. The bookmarklet only ever sees a
// small rotating slice, and only after a valid login.
//
// To swap in a new batch: replace the array below (one URL per line) and restart
// the server. Duplicates and obvious non-destination URLs are filtered at load
// time in server.js, so you can paste a raw dump without hand-cleaning it.
//
// Source dump label: AUTO GENERATED BY LINXTRA V1
// =============================================================================

module.exports = [
'https://quizizz.com/_media/dogeub/63ed3f3a-86c3-46a7-89b9-695474ff6e73-v2'
'https://wayground.com/_media/dogeub/63ed3f3a-86c3-46a7-89b9-695474ff6e73-v2'
'https://quizizz-static.s3.amazonaws.com/_media/dogeub/63ed3f3a-86c3-46a7-89b9-695474ff6e73-v2'
'https://quizizz-static.s3-accelerate.amazonaws.com/_media/dogeub/63ed3f3a-86c3-46a7-89b9-695474ff6e73-v2'
'https://media.blooket.com/raw/upload/gltfpql276tjshatwext.svg'
'https://media.blooket.com/raw/upload/ostdtyrul2rkg6glg8fa.html '
'https://edu.contratoslab.cl/'
'https://edu.ekivotos.gr/'
'https://edu.robertschulze.name/'
'https://edu.studio16.ru/'
'https://edu.it123.net/'
'https://eladesceelasobe-874571122136.us-west1.run.app/'
'https://mega-mega.cc.cd/'
'https://epic.kdns.fr/'
'https://s3.amazonaws.com/educationate/index.html'
'https://mathematics.2660010.com/'
'https://storage.googleapis.com/instructure/index.html'
'https://s3.amazonaws.com/deltamath-demo/index.html?scrlybrkr=3d45dcbe'
'https://s3.amazonaws.com/educationate/index.html'
'https://storage.googleapis.com/dogeub/index.html#/search'
'https://canvas-lms.storage.googleapis.com/index.html'
'https://edu.kavellewatches.com/'
'https://chicago.kavellewatches.com/'
'https://powerschooled.kavellewatches.com/'
'https://ti84.kavellewatches.com/'
'https://storage.googleapis.com/educationate/index.html'
'https://dogeub.storage.googleapis.com/index.html'
];
